# Generated by Django 3.1.6 on 2021-03-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210308_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='genre',
        ),
        migrations.AddField(
            model_name='profile',
            name='genre',
            field=models.CharField(default='', max_length=300),
        ),
    ]
