# Generated by Django 3.1.6 on 2021-03-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210308_2134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choices',
        ),
        migrations.AddField(
            model_name='profile',
            name='services',
            field=models.CharField(default='', max_length=300),
        ),
    ]
