# Generated by Django 3.1.6 on 2021-03-10 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210309_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='services',
            new_name='stream',
        ),
    ]
