# Generated by Django 3.1.6 on 2021-03-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210309_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='movies',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
