# Generated by Django 3.1.6 on 2021-03-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210309_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='movies',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
