# Generated by Django 3.1.6 on 2021-03-19 03:32

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210309_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='movies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Raya and the Last Dragon', 'https://image.tmdb.org/t/p/w200/lPsD10PP4rgUGiGR4CCXA6iY0QQ.jpg'), ('Sentinelle', 'https://image.tmdb.org/t/p/w200/fFRq98cW9lTo6di2o4lK1qUAWaN.jpg'), ('Below Zero', 'https://image.tmdb.org/t/p/w200/dWSnsAGTfc8U27bWsy2RfwZs0Bs.jpg'), ('Tom & Jerry', 'https://image.tmdb.org/t/p/w200/6KErczPBROQty7QoIsaa6wJYXZi.jpg'), ('Monster Hunter', 'https://image.tmdb.org/t/p/w200/1UCOF11QCw8kcqvce8LKOO6pimh.jpg'), ('Wonder Woman 1984', 'https://image.tmdb.org/t/p/w200/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg'), ('Coming 2 America', 'https://image.tmdb.org/t/p/w200/nWBPLkqNApY5pgrJFMiI9joSI30.jpg'), ('Space Sweepers', 'https://image.tmdb.org/t/p/w200/lykPQ7lgrLJPwLlSyetVXsl2wDf.jpg'), ("Zack Snyder's Justice League", 'https://image.tmdb.org/t/p/w200/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg')], max_length=152),
        ),
    ]
