# Generated by Django 3.1.7 on 2021-03-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210325_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='watchlater',
        ),
        migrations.AddField(
            model_name='profile',
            name='watchlater',
            field=models.ManyToManyField(to='users.WatchLaterEntry'),
        ),
    ]
