# Generated by Django 3.1.6 on 2021-03-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210318_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tv',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
