# Generated by Django 3.1.6 on 2021-03-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_tv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tv',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
