# Generated by Django 3.1.6 on 2021-03-28 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210325_2302'),
        ('users', '0016_auto_20210322_2257'),
    ]

    operations = [
    ]
