# Generated by Django 3.1.6 on 2021-03-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_merge_20210328_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='movies',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
